name: Build macOS .app

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip3 install pyinstaller

      - name: Build .app
        run: |
          pyinstaller --windowed --name FolderCreator FolderCreatorGUI_Updated_UI.py

      - name: Upload app artifact
        uses: actions/upload-artifact@v3
        with:
          name: FolderCreator_mac_app
          path: dist/FolderCreator.app
